## Pandas intro

In [3]:
import numpy as np
import pandas as pd

## Basic data structures in pandas
1)Series <br>
2)DataFrame

### Series

Series: a one-dimensional labeled array holding data of any type such as integers,string

In [3]:
#From ndarray
s = pd.Series([1, 3, 5, np.nan, 6, 8,9])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
6    9.0
dtype: float64

In [4]:
s1 = pd.Series(np.random.random(5),index=["a","b","c","d","e"])
s1

a    0.192951
b    0.659082
c    0.538849
d    0.876009
e    0.640152
dtype: float64

In [8]:
#From dict
s2 = {'a':43,'b':76,'c':32,'d':76}
pd.Series(s2)

a    43
b    76
c    32
d    76
dtype: int64

In [11]:
#Name Attribute
s1 = pd.Series(np.random.random(5),name="Random no.")
s1

0    0.601929
1    0.072957
2    0.694685
3    0.859868
4    0.124470
Name: Random no., dtype: float64

### Creating Dataframe

DataFrame: a two-dimensional data structure that holds data like a two-dimension array or a table with rows and columns.

In [10]:
#using list
student_data = [
    [100,80,10],
    [80,60,7],
    [120,100,14],
    [50,30,3]
]
pd.DataFrame(student_data,columns=['IQ','Marks','Package(LPA)'])

    IQ  Marks  Package(LPA)
0  100     80            10
1   80     60             7
2  120    100            14
3   50     30             3

## From dict of SeriesTo DataFrane

In [19]:
d = {
    "one":pd.Series([32,4,65,76,34]),
    "Two":pd.Series([65,87,43,88,35]),
    "Three":pd.Series([54,76,46,76,54])
}
df = pd.DataFrame(d)
df

   one  Two  Three
0   32   65     54
1    4   87     76
2   65   43     46
3   76   88     76
4   34   35     54

In [20]:
df1 = pd.DataFrame(d,columns=["Two","one"])
df1

   Two  one
0   65   32
1   87    4
2   43   65
3   88   76
4   35   34

In [9]:
student_info = {
    'Name':["Narendra Tekakel","Balaji Tekale","Priyanka Tekale","Bhagwat Tekale"],
    'Place':["Pune","Parbhani","Pune","Nanded"],
    'Role':["AIML","Mech","MSc","Msc"]
}
pd.DataFrame(student_info)

               Name     Place  Role
0  Narendra Tekakel      Pune  AIML
1     Balaji Tekale  Parbhani  Mech
2   Priyanka Tekale      Pune   MSc
3    Bhagwat Tekale    Nanded   Msc

### Viewing data
1)DataFrame.head() <br>
2)DataFrame.tail() <br>
3)DataFrame.index() <br>
4)DataFrame.columns() <br>
5)DataFrame.sort_index() <br>
6)DataFrame.sort_values()

In [22]:
long_series = pd.Series(np.random.randn(1000))
long_series.head()

0    0.185624
1    1.431684
2   -0.425058
3    0.697452
4   -0.877904
dtype: float64

In [24]:
long_series.head(3)

0    0.185624
1    1.431684
2   -0.425058
dtype: float64

In [25]:
long_series.tail()

995    0.907459
996   -0.266784
997    0.416183
998   -1.208537
999   -1.613911
dtype: float64

In [26]:
long_series.tail(3)

997    0.416183
998   -1.208537
999   -1.613911
dtype: float64

In [29]:
index = pd.date_range("1/1/2000", periods=8)
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=["A", "B", "C"])

In [40]:
df[:4]

                   A         B         C
2000-01-01 -0.186113  2.504863  0.370315
2000-01-02 -0.152263 -0.276427 -0.233096
2000-01-03  0.638853  0.603245 -0.156981
2000-01-04  0.575824  1.634270 -0.692593

## Descriptive statistics

In [58]:
s = pd.Series(np.round(np.random.random(10) * 10), index=["a", "b", "c", "d", "e","f","g","h","i","j"])
s

a    10.0
b     6.0
c     5.0
d     5.0
e     5.0
f     8.0
g     2.0
h     2.0
i     7.0
j     4.0
dtype: float64

In [60]:
#count = Number of non-NA observations
s.count()

10

In [61]:
#sum = sum of values
s.sum()

54.0

In [62]:
#mean = Mean of value
s.mean()

5.4

In [63]:
#median = Arithmetic median of values
s.median()

5.0

In [64]:
#mode = Mode
s.mode()

0    5.0
dtype: float64

In [65]:
s.min()

2.0

In [66]:
s.max()

10.0

In [67]:
#abs = Absolute Value
s.abs()

a    10.0
b     6.0
c     5.0
d     5.0
e     5.0
f     8.0
g     2.0
h     2.0
i     7.0
j     4.0
dtype: float64

In [68]:
#prod = Prodeuct values
s.prod()

6720000.0

In [69]:
#std = standard deviation
s.std()

2.503331114069145

In [70]:
#var = Unbiased variance
s.var()

6.266666666666667

In [71]:
#sem = Standard error of the mean
s.sem()

0.7916228058025278

In [72]:
#skew = Sample skewness (3rd moment)
s.skew()

0.33359805192580505

In [73]:
#kurt = Sample kurtosis (4th moment)
s.kurt()

-0.052625622453599696

In [76]:
#quantile = Sample quantile (value at %)
s.quantile()

5.0

In [77]:
#cumsum = Cumulative sum
s.cumsum()

a    10.0
b    16.0
c    21.0
d    26.0
e    31.0
f    39.0
g    41.0
h    43.0
i    50.0
j    54.0
dtype: float64

In [78]:
#cumprod = Cumulative product
s.cumprod()

a         10.0
b         60.0
c        300.0
d       1500.0
e       7500.0
f      60000.0
g     120000.0
h     240000.0
i    1680000.0
j    6720000.0
dtype: float64

## Summarizing data: describe

In [80]:
s.describe()

count    10.000000
mean      5.400000
std       2.503331
min       2.000000
25%       4.250000
50%       5.000000
75%       6.750000
max      10.000000
dtype: float64

## index of min/max values

In [81]:
#idxmin
s.idxmin()

'g'

In [82]:
#idxmax
s.idxmax()

'a'

## Value counts

In [83]:
s.value_counts()

5.0     3
2.0     2
10.0    1
6.0     1
8.0     1
7.0     1
4.0     1
Name: count, dtype: int64

## indexing and selecting data

In [86]:
#importing data set
movies = pd.read_csv('data/Movies.csv')
ipl = pd.read_csv('data/ipl.csv')

In [87]:
ipl.head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

## Campusx Tutorial

In [4]:
#importing data set
movies = pd.read_csv('data/Movies.csv')
movies
ipl = pd.read_csv('data/ipl.csv')
ipl

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [5]:
ipl.dtypes

id                   int64
city                object
date                object
player_of_match     object
venue               object
neutral_venue        int64
team1               object
team2               object
toss_winner         object
toss_decision       object
winner              object
result              object
result_margin      float64
eliminator          object
method              object
umpire1             object
umpire2             object
dtype: object

In [6]:
#shape
movies.shape
ipl.shape

(816, 17)

In [7]:
#dtypes
movies.dtypes

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object

In [9]:
#index
movies.index
ipl.index

RangeIndex(start=0, stop=816, step=1)

In [13]:
#colmns
list(movies.columns)
ipl.columns

Index(['id', 'city', 'date', 'player_of_match', 'venue', 'neutral_venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result',
       'result_margin', 'eliminator', 'method', 'umpire1', 'umpire2'],
      dtype='object')

In [ ]:
#head and tail
movies.head()
ipl.tail()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [14]:
#sample
#Random data
ipl.sample(10)
movies.sample(10)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1035,Yuvvraaj,tt1105747,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yuvvraaj,Yuvvraaj,Yuvvraaj,0,2008,151,Comedy|Drama|Romance,4.1,3707,Yogendra Yuvvraaj Singh lives a wealthy lifest...,Two estranged brothers must learn to work toge...,Music binds love,Salman Khan|Anil Kapoor|Zayed Khan|Mithun Chak...,1 win & 1 nomination,21 November 2008 (USA)
1279,My Wife's Murder,tt0451824,https://upload.wikimedia.org/wikipedia/en/d/d6...,https://en.wikipedia.org/wiki/My_Wife%27s_Murder,My Wife's Murder,My Wife's Murder,0,2005,103,Drama|Mystery|Thriller,6.2,834,Ravi Pathwardhan and editor lives middle class...,After a brief argument a husband accidentally...,NaN,Anil Kapoor|Suchitra Krishnamoorthi|Nandana Se...,NaN,19 August 2005 (India)
978,Rab Ne Bana Di Jodi,tt1182937,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Rab_Ne_Bana_Di_Jodi,Rab Ne Bana Di Jodi,Rab Ne Bana Di Jodi,0,2008,167,Comedy|Drama|Music,7.1,40973,Have you ever stopped to think if the most ord...,A breathtaking goose flesh igniting awe insp...,There is an extraordinary love story in every ...,Shah Rukh Khan|Anushka Sharma|Vinay Pathak|M.K...,4 wins & 14 nominations,12 December 2008 (USA)
1024,Saas Bahu Aur Sensex,tt1241334,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Saas_Bahu_Aur_Se...,Saas Bahu Aur Sensex,Saas Bahu Aur Sensex,0,2008,\N,Comedy|Drama,5.2,93,After a bitter divorce from her Kolkata-based ...,Upper middle-class women leave daytime soaps t...,NaN,Kiron Kher|Farooq Shaikh|Ankur Khanna|Masumeh ...,NaN,NaN
623,Siddharth (2013 film),tt2932606,https://upload.wikimedia.org/wikipedia/en/d/d7...,https://en.wikipedia.org/wiki/Siddharth_(2013_...,Siddharth,Siddharth,0,2013,96,Drama,7.3,582,After sending away his 12 year-old son Siddhar...,A chain-wallah from Delhi travels across India...,NaN,Rajesh Tailang|Tannishtha Chatterjee|Anurag Ar...,3 wins & 7 nominations,5 June 2014 (Israel)
300,7 Hours to Go,tt4365060,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/7_Hours_to_Go,7 Hours to Go,7 Hours to Go,0,2016,115,Crime|Thriller,5.7,357,Arjun (Shiv Pandit) come to Mumbai to visit hi...,The film is a fast paced investigative thrille...,The clock is ticking,Vipin Sharma|Sandeepa Dhar|Aakash Dabhade|Shiv...,NaN,24 June 2016 (India)
477,Ankhon Dekhi,tt3614516,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ankhon_Dekhi,Ankhon Dekhi,Ankhon Dekhi,0,2013,107,Comedy|Drama,8.0,8672,Raje Bauji (Sanjay Mishra) is a man in his lat...,Ankhon Dekhi centers around Raje Bauji played...,NaN,Sanjay Mishra|Seema Bhargava|Rajat Kapoor|Tara...,5 wins & 6 nominations,21 March 2014 (India)
122,Gold (2018 film),tt6173990,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gold_(2018_film),Gold,Gold,0,2018,151,Drama|History|Sport,7.3,10081,Tapan Das manager of Gold winning Indian hocke...,The journey of a man who was instrumental in m...,NaN,Akshay Kumar|Mouni Roy|Kunal Kapoor|Amit Sadh|...,3 wins & 3 nominations,15 August 2018 (USA)
975,Chandni Chowk to China,tt1091229,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Chandni_Chowk_to...,Chandni Chowk to China,Chandni Chowk to China,0,2009,154,Action|Comedy,4.0,7266,Based in Delhi's Chandni Chowk orphaned Sidhu...,An action-comedy about a simple cook from Chan...,This Diwali| two great civilizations... will w...,Mithun Chakraborty|Akshay Kumar|Deepika Paduko...,1 win & 3 nominations,16 January 2009 (USA)
1598,Kasam (2001 film),tt0317811,NaN,https://en.wikipedia.org/wiki/Kasam_(2001_film),Kasam,Kasam,0,2001,\N,Action|Drama,4.4,92,In aid of seeking revenge for his dad's death ...,In aid of seeking revenge for his dad's death ...,NaN,Naseeruddin Shah|Sunny Deol|Chunky Pandey|Neel...,NaN,NaN

In [21]:
#info
ipl.info()
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    object
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: float64(1), int64(2), object(14)
memory usage: 108.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

In [25]:
#describe
ipl.describe()

                 id  neutral_venue  result_margin
count  8.160000e+02     816.000000     799.000000
mean   7.563496e+05       0.094363      17.321652
std    3.058943e+05       0.292512      22.068427
min    3.359820e+05       0.000000       1.000000
25%    5.012278e+05       0.000000       6.000000
50%    7.292980e+05       0.000000       8.000000
75%    1.082626e+06       0.000000      19.500000
max    1.237181e+06       1.000000     146.000000

In [ ]:
#duplicated
#Identify repeated row in dataset
ipl.duplicated().sum()

0

In [16]:
ipl.isnull()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
812,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
813,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
814,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
815,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [31]:
ipl.isnull().sum()

id                   0
city                13
date                 0
player_of_match      4
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               4
result               4
result_margin       17
eliminator           4
method             797
umpire1              0
umpire2              0
dtype: int64

In [18]:
#rename
ipl.rename(columns={'player_of_match':'man_of_match','venue':'stadium'})

,id,city,date,man_of_match,stadium,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [40]:
#single col
ipl['city']

0       Bangalore
1      Chandigarh
2           Delhi
3          Mumbai
4         Kolkata
          ...
811         Dubai
812         Dubai
813     Abu Dhabi
814     Abu Dhabi
815         Dubai
Name: city, Length: 816, dtype: object

In [43]:
#multiple col
ipl[['date','team1','team2','winner','player_of_match']]

,date,team1,team2,winner,player_of_match
0,2008-04-18,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,BB McCullum
1,2008-04-19,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,MEK Hussey
2,2008-04-19,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,MF Maharoof
3,2008-04-20,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,MV Boucher
4,2008-04-20,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders,DJ Hussey
...,...,...,...,...,...
811,2020-09-28,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,AB de Villiers
812,2020-11-05,Mumbai Indians,Delhi Capitals,Mumbai Indians,JJ Bumrah
813,2020-11-06,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,KS Williamson
814,2020-11-08,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,MP Stoinis
815,2020-11-10,Delhi Capitals,Mumbai Indians,Mumbai Indians,TA Boult

In [ ]:
ipl.set_index('date')

,id,city,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
date,,,,,,,,,,,,,,,,
2008-04-18,335982,Bangalore,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
2008-04-19,335983,Chandigarh,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2008-04-19,335984,Delhi,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
2008-04-20,335985,Mumbai,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
2008-04-20,335986,Kolkata,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-09-28,1216547,Dubai,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
2020-11-05,1237177,Dubai,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
2020-11-06,1237178,Abu Dhabi,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
2020-11-08,1237180,Abu Dhabi,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
2020-11-10,1237181,Dubai,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [ ]:
#iloc[]=searches using index position
ipl.iloc[798]

id                                             1216534
city                                             Dubai
date                                        2020-09-21
player_of_match                              YS Chahal
venue              Dubai International Cricket Stadium
neutral_venue                                        0
team1                      Royal Challengers Bangalore
team2                              Sunrisers Hyderabad
toss_winner                        Sunrisers Hyderabad
toss_decision                                    field
winner                     Royal Challengers Bangalore
result                                            runs
result_margin                                     10.0
eliminator                                           N
method                                             NaN
umpire1                                    AY Dandekar
umpire2                                    Nitin Menon
Name: 798, dtype: object

In [ ]:
#loc[]=searches using index lable
ipl.loc[50:100]

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
50,336033,Chennai,2008-05-24,JA Morkel,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,bat,Rajasthan Royals,runs,10.0,N,NaN,DJ Harper,SL Shastri
51,336034,Bangalore,2008-05-03,P Kumar,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Deccan Chargers,Deccan Chargers,field,Royal Challengers Bangalore,runs,3.0,N,NaN,BR Doctrove,SL Shastri
52,336035,Kolkata,2008-05-25,Umar Gul,Eden Gardens,0,Kolkata Knight Riders,Kings XI Punjab,Kings XI Punjab,bat,Kolkata Knight Riders,wickets,3.0,N,NaN,SJ Davis,I Shivram
53,336036,Jaipur,2008-05-26,Sohail Tanvir,Sawai Mansingh Stadium,0,Rajasthan Royals,Mumbai Indians,Rajasthan Royals,field,Rajasthan Royals,wickets,5.0,N,NaN,BF Bowden,K Hariharan
54,336037,Hyderabad,2008-05-27,SK Raina,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Chennai Super Kings,Deccan Chargers,bat,Chennai Super Kings,wickets,7.0,N,NaN,BG Jerling,AM Saheba
55,336038,Mumbai,2008-05-30,SR Watson,Wankhede Stadium,0,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,field,Rajasthan Royals,runs,105.0,N,NaN,BF Bowden,RE Koertzen
56,336039,Mumbai,2008-05-31,M Ntini,Wankhede Stadium,0,Chennai Super Kings,Kings XI Punjab,Kings XI Punjab,bat,Chennai Super Kings,wickets,9.0,N,NaN,Asad Rauf,DJ Harper
57,336040,Mumbai,2008-06-01,YK Pathan,Dr DY Patil Sports Academy,0,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,3.0,N,NaN,BF Bowden,RE Koertzen
58,392181,Cape Town,2009-04-18,SR Tendulkar,Newlands,1,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,field,Mumbai Indians,runs,19.0,N,NaN,BR Doctrove,K Hariharan
59,392182,Cape Town,2009-04-18,R Dravid,Newlands,1,Royal Challengers Bangalore,Rajasthan Royals,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,75.0,N,NaN,BR Doctrove,RB Tiffin
60,392183,Cape Town,2009-04-19,DL Vettori,Newlands,1,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,field,Delhi Daredevils,wickets,10.0,N,D/L,MR Benson,SD Ranade
61,392184,Cape Town,2009-04-19,RP Singh,Newlands,1,Deccan Chargers,Kolkata Knight Riders,Kolkata Knight Riders,bat,Deccan Chargers,wickets,8.0,N,NaN,MR Benson,BR Doctrove
62,392185,Port Elizabeth,2009-04-20,M Muralitharan,St George's Park,1,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,92.0,N,NaN,BG Jerling,SJA Taufel
63,392186,Durban,2009-04-21,CH Gayle,Kingsmead,1,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,runs,11.0,N,D/L,DJ Harper,SD Ranade
64,392188,Cape Town,2009-04-22,AC Gilchrist,Newlands,1,Royal Challengers Bangalore,Deccan Chargers,Deccan Chargers,bat,Deccan Chargers,runs,24.0,N,NaN,M Erasmus,AM Saheba
65,392189,Durban,2009-04-23,AB de Villiers,Kingsmead,1,Chennai Super Kings,Delhi Daredevils,Delhi Daredevils,bat,Delhi Daredevils,runs,9.0,N,NaN,BR Doctrove,SJA Taufel
66,392190,Cape Town,2009-04-23,YK Pathan,Newlands,1,Kolkata Knight Riders,Rajasthan Royals,Kolkata Knight Riders,field,Rajasthan Royals,tie,NaN,Y,NaN,MR Benson,M Erasmus
67,392191,Durban,2009-04-24,RS Bopara,Kingsmead,1,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,wickets,7.0,N,NaN,BR Doctrove,TH Wijewardene
68,392192,Durban,2009-04-25,PP Ojha,Kingsmead,1,Deccan Chargers,Mumbai Indians,Deccan Chargers,bat,Deccan Chargers,runs,12.0,N,NaN,HDPK Dharmasena,SJA Taufel
69,392194,Port Elizabeth,2009-04-26,TM Dilshan,St George's Park,1,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,Delhi Daredevils,wickets,6.0,N,NaN,S Asnani,BG Jerling
70,392195,Cape Town,2009-04-26,KC Sangakkara,Newlands,1,Kings XI Punjab,Rajasthan Royals,Kings XI Punjab,bat,Kings XI Punjab,runs,27.0,N,NaN,M Erasmus,K Hariharan
71,392196,Durban,2009-04-27,HH Gibbs,Kingsmead,1,Chennai Super Kings,Deccan Chargers,Deccan Chargers,field,Deccan Chargers,wickets,6.0,N,NaN,IL Howell,TH Wijewardene
72,392197,Port Elizabeth,2009-04-27,SR Tendulkar,St George's Park,1,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,bat,Mumbai Indians,runs,92.0,N,NaN,BG Jerling,RB Tiffin
73,392198,Centurion,2009-04-28,YK Pathan,SuperSport Park,1,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,bat,Rajasthan Royals,wickets,5.0,N,NaN,GAV Baxter,RE Koertzen
74,392199,Durban,2009-04-29,MV Boucher,Kingsmead,1,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,MR Benson,TH Wijewardene
75,392200,Durban,2009-04-29,KC Sangakkara,Kingsmead,1,Kings XI Punjab,Mumbai Indians,Kings XI Punjab,bat,Kings XI Punjab,runs,3.0,N,NaN,MR Benson,SL Shastri
76,392201,Centurion,2009-04-30,DP Nannes,SuperSport Park,1,Deccan Chargers,Delhi Daredevils,Delhi Daredevils,field,Delhi Daredevils,wickets,6.0,N,NaN,GAV Baxter,AM Saheba
77,392202,Centurion,2009-04-30,SK Raina,SuperSport Park,1,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,Chennai Super Kings,runs,38.0,N,NaN,GAV Baxter,RE Koertzen
78,392203,East London,2009-05-01,JP Duminy,Buffalo Park,1,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,bat,Mumbai Indians,runs,9.0,N,NaN,M Erasmus,SK Tarapore
79,392204,Durban,2009-05-01,Yuvraj Singh,Kingsmead,1,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,8.0,N,NaN,HDPK Dharmasena,S Ravi
80,392205,Port Elizabeth,2009-05-02,YK Pathan,St George's Park,1,Deccan Chargers,Rajasthan Royals,Deccan Chargers,bat,Rajasthan Royals,wickets,3.0,N,NaN,S Asnani,BG Jerling
81,392206,Johannesburg,2009-05-02,SB Jakati,New Wanderers Stadium,1,Chennai Super Kings,Delhi Daredevils,Delhi Daredevils,field,Chennai Super Kings,runs,18.0,N,NaN,DJ Harper,RE Koertzen
82,392207,Port Elizabeth,2009-05-03,DPMD Jayawardene,St George's Park,1,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,bat,Kings XI Punjab,wickets,6.0,N,NaN,S Asnani,MR Benson
83,392208,Johannesburg,2009-05-03,JH Kallis,New Wanderers Stadium,1,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,9.0,N,NaN,RE Koertzen,TH Wijewardene
84,392209,East London,2009-05-04,MS Dhoni,Buffalo Park,1,Chennai Super Kings,Deccan Chargers,Chennai Super Kings,bat,Chennai Super Kings,runs,78.0,N,NaN,BR Doctrove,M Erasmus
85,392210,Durban,2009-05-05,GC Smith,Kingsmead,1,Kings XI Punjab,Rajasthan Royals,Kings XI Punjab,field,Rajasthan Royals,runs,78.0,N,NaN,SS Hazare,IL Howell
86,392211,Durban,2009-05-05,G Gambhir,Kingsmead,1,Delhi Daredevils,Kolkata Knight Riders,Kolkata Knight Riders,bat,Delhi Daredevils,wickets,9.0,N,NaN,GAV Baxter,IL Howell
87,392212,Centurion,2009-05-06,RG Sharma,SuperSport Park,1,Deccan Chargers,Mumbai Indians,Deccan Chargers,bat,Deccan Chargers,runs,19.0,N,NaN,MR Benson,HDPK Dharmasena
88,392213,Centurion,2009-05-07,A Singh,SuperSport Park,1,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,7.0,N,NaN,K Hariharan,DJ Harper
89,392214,Centurion,2009-05-07,ML Hayden,SuperSport Park,1,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,Chennai Super Kings,runs,12.0,N,D/L,DJ Harper,TH Wijewardene
90,392215,East London,2009-05-08,A Nehra,Buffalo Park,1,Delhi Daredevils,Mumbai Indians,Mumbai Indians,bat,Delhi Daredevils,wickets,7.0,N,NaN,M Erasmus,SK Tarapore
91,392216,Kimberley,2009-05-09,DPMD Jayawardene,De Beers Diamond Oval,1,Deccan Chargers,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,3.0,N,NaN,GAV Baxter,AM Saheba
92,392217,Kimberley,2009-05-09,S Badrinath,De Beers Diamond Oval,1,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,bat,Chennai Super Kings,wickets,7.0,N,NaN,GAV Baxter,HDPK Dharmasena
93,392218,Port Elizabeth,2009-05-10,JP Duminy,St George's Park,1,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,bat,Mumbai Indians,runs,16.0,N,NaN,BR Doctrove,BG Jerling
94,392219,Johannesburg,2009-05-10,A Mishra,New Wanderers Stadium,1,Delhi Daredevils,Kolkata Knight Riders,Delhi Daredevils,field,Delhi Daredevils,wickets,7.0,N,NaN,SL Shastri,RB Tiffin
95,392220,Kimberley,2009-05-11,DR Smith,De Beers Diamond Oval,1,Deccan Chargers,Rajasthan Royals,Deccan Chargers,bat,Deccan Chargers,runs,53.0,N,NaN,GAV Baxter,HDPK Dharmasena
96,392221,Centurion,2009-05-12,LRPL Taylor,SuperSport Park,1,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,6.0,N,NaN,M Erasmus,SS Hazare
97,392222,Centurion,2009-05-12,Harbhajan Singh,SuperSport Park,1,Kings XI Punjab,Mumbai Indians,Kings XI Punjab,bat,Mumbai Indians,wickets,8.0,N,NaN,SS Hazare,RE Koertzen
98,392223,Durban,2009-05-13,R Bhatia,Kingsmead,1,Deccan Chargers,Delhi Daredevils,Deccan Chargers,field,Delhi Daredevils,runs,12.0,N,NaN,DJ Harper,SL Shastri
99,392224,Durban,2009-05-14,LRPL Taylor,Kingsmead,1,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,bat,Royal Challengers Bangalore,wickets,2.0,N,NaN,BR Doctrove,DJ Harper
100,392225,Durban,2009-05-14,SK Warne,Kingsmead,1,Mumbai Indians,Rajasthan Royals,Rajasthan Royals,bat,Rajasthan Royals,runs,2.0,N,NaN,BR Doctrove,DJ Harper

In [ ]:
#Fancy indexing
ipl.iloc[[1,4,7,34,65,87,445,655,800]]

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
7,335989,Chennai,2008-04-23,ML Hayden,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings,runs,6.0,N,NaN,DJ Harper,GA Pratapkumar
34,336016,Chandigarh,2008-05-12,SE Marsh,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Kings XI Punjab,wickets,9.0,N,NaN,BR Doctrove,I Shivram
65,392189,Durban,2009-04-23,AB de Villiers,Kingsmead,1,Chennai Super Kings,Delhi Daredevils,Delhi Daredevils,bat,Delhi Daredevils,runs,9.0,N,NaN,BR Doctrove,SJA Taufel
87,392212,Centurion,2009-05-06,RG Sharma,SuperSport Park,1,Deccan Chargers,Mumbai Indians,Deccan Chargers,bat,Deccan Chargers,runs,19.0,N,NaN,MR Benson,HDPK Dharmasena
445,734025,Chandigarh,2014-05-21,LMP Simmons,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,7.0,N,NaN,HDPK Dharmasena,VA Kulkarni
655,1136580,Hyderabad,2018-04-22,AT Rayudu,"Rajiv Gandhi International Stadium, Uppal",0,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,field,Chennai Super Kings,runs,4.0,N,NaN,VA Kulkarni,AK Chaudhary
800,1216536,Dubai,2020-10-29,RD Gaikwad,Dubai International Cricket Stadium,0,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,6.0,N,NaN,C Shamshuddin,RK Illingworth

In [ ]:
#Selecting both row and column
ipl.iloc[10:21,6:11]

,team1,team2,toss_winner,toss_decision,winner
10,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals
11,Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,bat,Chennai Super Kings
12,Mumbai Indians,Deccan Chargers,Deccan Chargers,field,Deccan Chargers
13,Kings XI Punjab,Delhi Daredevils,Delhi Daredevils,bat,Kings XI Punjab
14,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings
15,Kolkata Knight Riders,Mumbai Indians,Kolkata Knight Riders,bat,Mumbai Indians
16,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Delhi Daredevils
17,Deccan Chargers,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab
18,Rajasthan Royals,Kolkata Knight Riders,Rajasthan Royals,bat,Rajasthan Royals
19,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings,bat,Delhi Daredevils
20,Deccan Chargers,Royal Challengers Bangalore,Deccan Chargers,bat,Royal Challengers Bangalore

In [ ]:
#find all RCB winning macth 
rcb = ipl['winner'] == 'Royal Challengers Bangalore'
ipl[rcb]

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
20,336002,Hyderabad,2008-05-25,R Vinay Kumar,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Royal Challengers Bangalore,Deccan Chargers,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,Asad Rauf,RE Koertzen
47,336029,Chennai,2008-05-21,A Kumble,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,14.0,N,NaN,DJ Harper,I Shivram
51,336034,Bangalore,2008-05-03,P Kumar,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Deccan Chargers,Deccan Chargers,field,Royal Challengers Bangalore,runs,3.0,N,NaN,BR Doctrove,SL Shastri
59,392182,Cape Town,2009-04-18,R Dravid,Newlands,1,Royal Challengers Bangalore,Rajasthan Royals,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,75.0,N,NaN,BR Doctrove,RB Tiffin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
786,1216522,Dubai,2020-10-17,AB de Villiers,Dubai International Cricket Stadium,0,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,bat,Royal Challengers Bangalore,wickets,7.0,N,NaN,AK Chaudhary,Nitin Menon
789,1216525,Dubai,2020-10-10,V Kohli,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,37.0,N,NaN,AK Chaudhary,PR Reiffel
798,1216534,Dubai,2020-09-21,YS Chahal,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Royal Challengers Bangalore,runs,10.0,N,NaN,AY Dandekar,Nitin Menon
804,1216540,Sharjah,2020-10-12,AB de Villiers,Sharjah Cricket Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,82.0,N,NaN,RK Illingworth,K Srinivasan
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel

In [45]:
mi=ipl['winner']=='Mumbai Indians'
ipl[mi]

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
15,335997,Kolkata,2008-04-29,ST Jayasuriya,Eden Gardens,0,Kolkata Knight Riders,Mumbai Indians,Kolkata Knight Riders,bat,Mumbai Indians,wickets,7.0,N,NaN,BF Bowden,AV Jayaprakash
22,336004,Mumbai,2008-05-04,SM Pollock,Dr DY Patil Sports Academy,0,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,Mumbai Indians,runs,29.0,N,NaN,IL Howell,RE Koertzen
26,336008,Mumbai,2008-05-07,A Nehra,Dr DY Patil Sports Academy,0,Mumbai Indians,Rajasthan Royals,Mumbai Indians,field,Mumbai Indians,wickets,7.0,N,NaN,DJ Harper,RE Koertzen
30,336012,Bangalore,2008-05-28,CRD Fernando,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,9.0,N,NaN,BF Bowden,AV Jayaprakash
36,336018,Mumbai,2008-05-14,ST Jayasuriya,Wankhede Stadium,0,Mumbai Indians,Chennai Super Kings,Mumbai Indians,field,Mumbai Indians,wickets,9.0,N,NaN,BR Doctrove,AM Saheba
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
793,1216529,Abu Dhabi,2020-10-11,Q de Kock,Sheikh Zayed Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,S Ravi
799,1216535,Dubai,2020-10-31,Ishan Kishan,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,9.0,N,NaN,YC Barde,PR Reiffel
802,1216538,Sharjah,2020-10-04,TA Boult,Sharjah Cricket Stadium,0,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,Mumbai Indians,runs,34.0,N,NaN,KN Ananthapadmanabhan,RK Illingworth
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [46]:
#All macth in which rohit sharma is man of macth
Rohit = ipl['player_of_match'] == 'RG Sharma'
ipl[Rohit]

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
87,392212,Centurion,2009-05-06,RG Sharma,SuperSport Park,1,Deccan Chargers,Mumbai Indians,Deccan Chargers,bat,Deccan Chargers,runs,19.0,N,NaN,MR Benson,HDPK Dharmasena
103,392228,Johannesburg,2009-05-16,RG Sharma,New Wanderers Stadium,1,Deccan Chargers,Kolkata Knight Riders,Deccan Chargers,field,Deccan Chargers,wickets,6.0,N,NaN,RE Koertzen,S Ravi
165,419156,Dharamsala,2010-04-16,RG Sharma,Himachal Pradesh Cricket Association Stadium,0,Kings XI Punjab,Deccan Chargers,Deccan Chargers,field,Deccan Chargers,wickets,5.0,N,NaN,M Erasmus,AM Saheba
256,548314,Visakhapatnam,2012-04-09,RG Sharma,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,0,Deccan Chargers,Mumbai Indians,Deccan Chargers,bat,Mumbai Indians,wickets,5.0,N,NaN,AK Chaudhary,JD Cloete
303,548363,Kolkata,2012-05-12,RG Sharma,Eden Gardens,0,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,bat,Mumbai Indians,runs,27.0,N,NaN,S Ravi,SJA Taufel
335,598011,Mumbai,2013-04-13,RG Sharma,Wankhede Stadium,0,Mumbai Indians,Pune Warriors,Mumbai Indians,bat,Mumbai Indians,runs,41.0,N,NaN,S Ravi,SJA Taufel
361,598037,Mumbai,2013-04-29,RG Sharma,Wankhede Stadium,0,Mumbai Indians,Kings XI Punjab,Mumbai Indians,bat,Mumbai Indians,runs,4.0,N,NaN,Asad Rauf,AK Chaudhary
424,733983,Mumbai,2014-05-06,RG Sharma,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Mumbai Indians,runs,19.0,N,NaN,S Ravi,K Srinath
516,829823,Kolkata,2015-05-24,RG Sharma,Eden Gardens,0,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,Mumbai Indians,runs,41.0,N,NaN,HDPK Dharmasena,RK Illingworth
521,980909,Kolkata,2016-04-13,RG Sharma,Eden Gardens,0,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,6.0,N,NaN,Nitin Menon,S Ravi
530,980927,Mumbai,2016-04-20,RG Sharma,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,field,Mumbai Indians,wickets,6.0,N,NaN,AK Chaudhary,CK Nandan
540,980947,Mumbai,2016-04-28,RG Sharma,Wankhede Stadium,0,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians,field,Mumbai Indians,wickets,6.0,N,NaN,Nitin Menon,RJ Tucker
545,980957,Pune,2016-05-01,RG Sharma,Maharashtra Cricket Association Stadium,0,Rising Pune Supergiants,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,8.0,N,NaN,AY Dandekar,RJ Tucker
613,1082628,Mumbai,2017-05-01,RG Sharma,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Mumbai Indians,wickets,5.0,N,NaN,AK Chaudhary,CB Gaffaney
649,1136574,Mumbai,2018-04-17,RG Sharma,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Mumbai Indians,runs,46.0,N,NaN,RJ Tucker,Nitin Menon
662,1136587,Pune,2018-04-28,RG Sharma,Maharashtra Cricket Association Stadium,0,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,8.0,N,NaN,CB Gaffaney,Nitin Menon
739,1178419,Chennai,2019-04-26,RG Sharma,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,field,Mumbai Indians,runs,46.0,N,NaN,NJ Llong,AK Chaudhary
772,1216508,Abu Dhabi,2020-09-23,RG Sharma,Sheikh Zayed Stadium,0,Mumbai Indians,Kolkata Knight Riders,Kolkata Knight Riders,field,Mumbai Indians,runs,49.0,N,NaN,CB Gaffaney,S Ravi

In [ ]:
new1=ipl[(ipl['city']=='Mumbai') & (ipl['winner']=='Mumbai IndiANS')]

In [ ]:
#All RCB winning macth in bangalore
new = ipl[(ipl['city'] == 'Bangalore') & (ipl['winner'] == 'Royal Challengers Bangalore')]
new

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
51,336034,Bangalore,2008-05-03,P Kumar,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Deccan Chargers,Deccan Chargers,field,Royal Challengers Bangalore,runs,3.0,N,NaN,BR Doctrove,SL Shastri
121,419112,Bangalore,2010-03-16,JH Kallis,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,bat,Royal Challengers Bangalore,wickets,8.0,N,NaN,S Das,DJ Harper
124,419115,Bangalore,2010-03-18,JH Kallis,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Rajasthan Royals,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,10.0,N,NaN,K Hariharan,DJ Harper
132,419123,Bangalore,2010-03-23,RV Uthappa,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,field,Royal Challengers Bangalore,runs,36.0,N,NaN,RE Koertzen,RB Tiffin
157,419148,Bangalore,2010-04-10,R Vinay Kumar,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,7.0,N,NaN,K Hariharan,DJ Harper
208,501232,Bangalore,2011-04-29,V Kohli,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Pune Warriors,Pune Warriors,field,Royal Challengers Bangalore,runs,26.0,N,NaN,Aleem Dar,SS Hazare
220,501244,Bangalore,2011-05-06,CH Gayle,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,Royal Challengers Bangalore,runs,85.0,N,NaN,Aleem Dar,RB Tiffin
223,501247,Bangalore,2011-05-08,CH Gayle,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kochi Tuskers Kerala,Kochi Tuskers Kerala,bat,Royal Challengers Bangalore,wickets,9.0,N,NaN,Aleem Dar,SS Hazare
231,501255,Bangalore,2011-05-14,CH Gayle,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,4.0,N,D/L,RE Koertzen,RB Tiffin
242,501266,Bangalore,2011-05-22,CH Gayle,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,8.0,N,NaN,K Hariharan,RE Koertzen
252,548310,Bangalore,2012-04-07,AB de Villiers,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Delhi Daredevils,Delhi Daredevils,field,Royal Challengers Bangalore,runs,20.0,N,NaN,S Asnani,S Ravi
269,548327,Bangalore,2012-04-17,CH Gayle,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Pune Warriors,Pune Warriors,bat,Royal Challengers Bangalore,wickets,6.0,N,NaN,S Asnani,S Das
296,548356,Bangalore,2012-05-06,AB de Villiers,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Deccan Chargers,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,5.0,N,NaN,HDPK Dharmasena,BNJ Oxenford
323,597999,Bangalore,2013-04-04,CH Gayle,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,runs,2.0,N,NaN,VA Kulkarni,C Shamshuddin
332,598008,Bangalore,2013-04-11,CH Gayle,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,8.0,N,NaN,Asad Rauf,AK Chaudhary
341,598017,Bangalore,2013-04-16,V Kohli,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,M Erasmus,VA Kulkarni
347,598023,Bangalore,2013-04-20,R Vinay Kumar,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Rajasthan Royals,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,7.0,N,NaN,Aleem Dar,C Shamshuddin
351,598027,Bangalore,2013-04-23,CH Gayle,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Pune Warriors,Pune Warriors,field,Royal Challengers Bangalore,runs,130.0,N,NaN,Aleem Dar,C Shamshuddin
372,598048,Bangalore,2013-04-09,V Kohli,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,bat,Royal Challengers Bangalore,wickets,7.0,N,NaN,S Ravi,SJA Taufel
392,598068,Bangalore,2013-05-18,V Kohli,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,field,Royal Challengers Bangalore,runs,24.0,N,NaN,C Shamshuddin,RJ Tucker
421,733977,Bangalore,2014-05-04,AB de Villiers,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,4.0,N,NaN,HDPK Dharmasena,VA Kulkarni
435,734005,Bangalore,2014-05-13,Yuvraj Singh,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Delhi Daredevils,Delhi Daredevils,field,Royal Challengers Bangalore,runs,16.0,N,NaN,K Srinath,RJ Tucker
490,829771,Bangalore,2015-05-02,Mandeep Singh,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,7.0,N,NaN,JD Cloete,PG Pathak
497,829785,Bangalore,2015-05-06,CH Gayle,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,Royal Challengers Bangalore,runs,138.0,N,NaN,RK Illingworth,VA Kulkarni
520,980907,Bangalore,2016-04-12,AB de Villiers,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Royal Challengers Bangalore,runs,45.0,N,NaN,HDPK Dharmasena,VK Sharma
551,980969,Bangalore,2016-05-07,V Kohli,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Rising Pune Supergiants,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,7.0,N,NaN,CB Gaffaney,BNJ Oxenford
560,980987,Bangalore,2016-05-14,AB de Villiers,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,field,Royal Challengers Bangalore,runs,144.0,N,NaN,AY Dandekar,VK Sharma
566,980999,Bangalore,2016-05-18,V Kohli,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,Royal Challengers Bangalore,runs,82.0,N,D/L,KN Ananthapadmanabhan,M Erasmus
573,981013,Bangalore,2016-05-24,AB de Villiers,M Chinnaswamy Stadium,0,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,4.0,N,NaN,AK Chaudhary,HDPK Dharmasena

In [6]:
#toss winner is macth winner in percentage
(ipl[ipl['toss_winner'] == ipl['winner']].shape[0]/ipl.shape[0])*100

51.225490196078425

In [10]:
#Creating new column
movies['Country'] = 'India'
movies.head(7)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,Country
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),India
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),India
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA),India
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA),India
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India),India
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA),India
6,Fraud Saiyaan,tt5013008,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Fraud_Saiyaan,Fraud Saiyaan,Fraud Saiyyan,0,2019,109,Comedy|Drama,4.2,504,Fraud Saiyyan is the story of a con artist in ...,Fraud Saiyyan is the story of a con artist in ...,NaN,Arshad Warsi|Saurabh Shukla|Flora Saini|Sara L...,NaN,18 January 2019 (India),India

In [12]:
#astype
#reducing the size of data set by changing data type
ipl['id'] = ipl['id'].astype('int32')
ipl['neutral_venue'] = ipl['neutral_venue'].astype('int32')
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int32
 1   city             803 non-null    object
 2   date             816 non-null    object
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int32
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: float64(1), int32(2), object(14)
memory usage: 102.1+ KB