In [1]:
#Multi-index Dataframe
import pandas as pd
import numpy as np
# can we have multiple index? Let's try
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
a = pd.Series([1,2,3,4,5,6,7,8],index=index_val)
a

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [2]:
a['cse' ,2020]

2

In [3]:
#the problem
#a['cse']

In [4]:
#The solution is multiindex series (is also know as Hierarchical Indexing)
#multiple index leveks within a single index

In [5]:
#How to create multiindex object
#1.pd.MultiIndex.from_tuples()
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
multiindex = pd.MultiIndex.from_tuples(index_val)
multiindex.levels[0]
#2.pd.MultiIndex.from_product()
pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [6]:
#access the index
multiindex.levels
#multiindex.levels[0]
#multiindex.levels[1]

FrozenList([['cse', 'ece'], [2019, 2020, 2021, 2022]])

In [7]:
#create a series
s=pd.Series([1,2,3,4,5,6,7,8],index=multiindex)
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [8]:
s['cse']

2019    1
2020    2
2021    3
2022    4
dtype: int64

In [9]:
s[('cse', 2022)]

4

In [10]:
#unstack = row to column
temp = s.unstack()
temp

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [11]:
#stack = column to roe
s = temp.stack()
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [12]:
#multiindex of from row perspective
branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],
    index = multiindex,
    columns =['avg_package','student'])

branch_df1

          avg_package  student
cse 2019            1        2
    2020            3        4
    2021            5        6
    2022            7        8
ece 2019            9       10
    2020           11       12
    2021           13       14
    2022           15       16

In [13]:
#multiindex of from columns prespective
column_multiindex = pd.DataFrame([
    [32,5,46,6],
    [23,4,45,5],
    [31,5,28,4],
    [51,8,76,9]
],index = [2019,2020,2021,2022],
columns= pd.MultiIndex.from_product([['Pune','Mumbai'],['avg_package','student']])
)
column_multiindex

            Pune              Mumbai
     avg_package student avg_package student
2019          32       5          46       6
2020          23       4          45       5
2021          31       5          28       4
2022          51       8          76       9

In [14]:
#multiindexing on column and row
temp_df = pd.DataFrame([
    [32,5,46,6],
    [23,4,45,5],
    [31,5,28,4],
    [51,8,76,9],
    [43,5,65,4],
    [76,4,23,5],
    [76,5,43,7],
    [54,7,34,2]
],index = pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]]),
columns = pd.MultiIndex.from_product([['Pune','Mumbai'],['avg_package','student']]))
temp_df

                Pune              Mumbai
         avg_package student avg_package student
cse 2019          32       5          46       6
    2020          23       4          45       5
    2021          31       5          28       4
    2022          51       8          76       9
ece 2019          43       5          65       4
    2020          76       4          23       5
    2021          76       5          43       7
    2022          54       7          34       2

### stack and  unstack

In [15]:
branch_df1

          avg_package  student
cse 2019            1        2
    2020            3        4
    2021            5        6
    2022            7        8
ece 2019            9       10
    2020           11       12
    2021           13       14
    2022           15       16

In [16]:
branch_df1.unstack()

    avg_package                student
           2019 2020 2021 2022    2019 2020 2021 2022
cse           1    3    5    7       2    4    6    8
ece           9   11   13   15      10   12   14   16

In [17]:
branch_df1.unstack().unstack()

avg_package  2019  cse     1
                   ece     9
             2020  cse     3
                   ece    11
             2021  cse     5
                   ece    13
             2022  cse     7
                   ece    15
student      2019  cse     2
                   ece    10
             2020  cse     4
                   ece    12
             2021  cse     6
                   ece    14
             2022  cse     8
                   ece    16
dtype: int64

In [18]:
branch_df1.unstack().stack()

C:\Users\narendra tekale\AppData\Local\Temp\ipykernel_25972\1991893145.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df1.unstack().stack()

          avg_package  student
cse 2019            1        2
    2020            3        4
    2021            5        6
    2022            7        8
ece 2019            9       10
    2020           11       12
    2021           13       14
    2022           15       16

In [19]:
branch_df1.unstack().stack().stack()

C:\Users\narendra tekale\AppData\Local\Temp\ipykernel_25972\2994828746.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df1.unstack().stack().stack()

cse  2019  avg_package     1
           student         2
     2020  avg_package     3
           student         4
     2021  avg_package     5
           student         6
     2022  avg_package     7
           student         8
ece  2019  avg_package     9
           student        10
     2020  avg_package    11
           student        12
     2021  avg_package    13
           student        14
     2022  avg_package    15
           student        16
dtype: int64

In [20]:
temp_df.unstack()

           Pune                                            Mumbai            \
    avg_package                student                avg_package
           2019 2020 2021 2022    2019 2020 2021 2022        2019 2020 2021
cse          32   23   31   51       5    4    5    8          46   45   28
ece          43   76   76   54       5    4    5    7          65   23   43


         student
    2022    2019 2020 2021 2022
cse   76       6    5    4    9
ece   34       4    5    7    2

In [21]:
temp_df.stack()

C:\Users\narendra tekale\AppData\Local\Temp\ipykernel_25972\1362379900.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  temp_df.stack()

                      Pune  Mumbai
cse 2019 avg_package    32      46
         student         5       6
    2020 avg_package    23      45
         student         4       5
    2021 avg_package    31      28
         student         5       4
    2022 avg_package    51      76
         student         8       9
ece 2019 avg_package    43      65
         student         5       4
    2020 avg_package    76      23
         student         4       5
    2021 avg_package    76      43
         student         5       7
    2022 avg_package    54      34
         student         7       2

In [22]:
temp_df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8 entries, ('cse', 2019) to ('ece', 2022)
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (Pune, avg_package)    8 non-null      int64
 1   (Pune, student)        8 non-null      int64
 2   (Mumbai, avg_package)  8 non-null      int64
 3   (Mumbai, student)      8 non-null      int64
dtypes: int64(4)
memory usage: 632.0+ bytes

In [23]:
#extract single row
temp_df.loc[('cse',2022)]

Pune    avg_package    51
        student         8
Mumbai  avg_package    76
        student         9
Name: (cse, 2022), dtype: int64

In [24]:
temp_df.loc[('cse',2019):('ece',2019):2]

                Pune              Mumbai
         avg_package student avg_package student
cse 2019          32       5          46       6
    2021          31       5          28       4
ece 2019          43       5          65       4

In [25]:
temp_df.iloc[0:5:2]

                Pune              Mumbai
         avg_package student avg_package student
cse 2019          32       5          46       6
    2021          31       5          28       4
ece 2019          43       5          65       4

In [26]:
temp_df.iloc[:,1:3]

            Pune      Mumbai
         student avg_package
cse 2019       5          46
    2020       4          45
    2021       5          28
    2022       8          76
ece 2019       5          65
    2020       4          23
    2021       5          43
    2022       7          34

In [27]:
#fancy indexing
temp_df.iloc[[0,4],[1,2]]

            Pune      Mumbai
         student avg_package
cse 2019       5          46
ece 2019       5          65

In [28]:
#sorting 
temp_df.sort_index(ascending=False)

                Pune              Mumbai
         avg_package student avg_package student
ece 2022          54       7          34       2
    2021          76       5          43       7
    2020          76       4          23       5
    2019          43       5          65       4
cse 2022          51       8          76       9
    2021          31       5          28       4
    2020          23       4          45       5
    2019          32       5          46       6

In [29]:
#swap the index levels
temp_df.swaplevel()

                Pune              Mumbai
         avg_package student avg_package student
2019 cse          32       5          46       6
2020 cse          23       4          45       5
2021 cse          31       5          28       4
2022 cse          51       8          76       9
2019 ece          43       5          65       4
2020 ece          76       4          23       5
2021 ece          76       5          43       7
2022 ece          54       7          34       2

In [30]:
#Transpose 
temp_df.transpose()

                    cse                 ece
                   2019 2020 2021 2022 2019 2020 2021 2022
Pune   avg_package   32   23   31   51   43   76   76   54
       student        5    4    5    8    5    4    5    7
Mumbai avg_package   46   45   28   76   65   23   43   34
       student        6    5    4    9    4    5    7    2

In [31]:
#swap the columns index
temp_df.swaplevel(axis=1)

         avg_package student avg_package student
                Pune    Pune      Mumbai  Mumbai
cse 2019          32       5          46       6
    2020          23       4          45       5
    2021          31       5          28       4
    2022          51       8          76       9
ece 2019          43       5          65       4
    2020          76       4          23       5
    2021          76       5          43       7
    2022          54       7          34       2

In [32]:
#melt = wide to long
#simple example
pd.DataFrame({'cse':[120]}).melt()

  variable  value
0      cse    120

In [33]:
x = pd.DataFrame({'cse':[120],'mech':[180],'AIML':[60],'AIDS':[120]})
x

   cse  mech  AIML  AIDS
0  120   180    60   120

In [34]:
x.melt()

  variable  value
0      cse    120
1     mech    180
2     AIML     60
3     AIDS    120

In [35]:
x.melt(var_name='Brach',value_name='No.of Student')

  Brach  No.of Student
0   cse            120
1  mech            180
2  AIML             60
3  AIDS            120

In [36]:
df1 = pd.DataFrame(
{
    'Branch':['CSE','AIML','IT','AIDS'],
    '2020':[120,60,120,60],
    '2021':[120,75,120,75],
    '2022':[180,80,180,100],
    '2023':[180,75,180,120]
})
df1.melt()
#this is not good format

   variable value
0    Branch   CSE
1    Branch  AIML
2    Branch    IT
3    Branch  AIDS
4      2020   120
5      2020    60
6      2020   120
7      2020    60
8      2021   120
9      2021    75
10     2021   120
11     2021    75
12     2022   180
13     2022    80
14     2022   180
15     2022   100
16     2023   180
17     2023    75
18     2023   180
19     2023   120

In [37]:
#id_vars prevent the column to transform
df1.melt(id_vars=['Branch'],var_name='Year',value_name='Seat')

   Branch  Year  Seat
0     CSE  2020   120
1    AIML  2020    60
2      IT  2020   120
3    AIDS  2020    60
4     CSE  2021   120
5    AIML  2021    75
6      IT  2021   120
7    AIDS  2021    75
8     CSE  2022   180
9    AIML  2022    80
10     IT  2022   180
11   AIDS  2022   100
12    CSE  2023   180
13   AIML  2023    75
14     IT  2023   180
15   AIDS  2023   120

In [38]:
#real word data example
confirmed = pd.read_csv('data/time_series_covid19_confirmed_global.csv')
death = pd.read_csv('data/time_series_covid19_deaths_global.csv')

In [39]:
death

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,6881,6881,6881,6881,6881,6881,6881,6881,6881,6881
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,165
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,1928,1928,1928,1930,1930,1930,1930,1930,1930,1930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,5708,5708,5708,5708,5708,5708,5708,5708,5708,5708
285,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
286,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,2159,2159,2159,2159,2159,2159,2159,2159,2159,2159
287,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,4019,4019,4022,4022,4023,4023,4024,4024,4024,4024
288,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,5637,5637,5637,5637,5637,5637,5637,5637,5637,5637

In [40]:
confirmed

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,207310,207399,207438,207460,207493,207511,207550,207559,207616,207627
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,333749,333749,333751,333751,333776,333776,333806,333806,333811,333812
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,271194,271198,271198,271202,271208,271217,271223,271228,271229,271229
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,47686,47686,47686,47686,47751,47751,47751,47751,47751,47751
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,104973,104973,104973,105095,105095,105095,105095,105095,105095,105095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,703228,703228,703228,703228,703228,703228,703228,703228,703228,703228
285,NaN,Winter Olympics 2022,39.904200,116.407400,0,0,0,0,0,0,...,535,535,535,535,535,535,535,535,535,535
286,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,11945,11945,11945,11945,11945,11945,11945,11945,11945,11945
287,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,334021,334021,334066,334108,334196,334294,334425,334425,334629,334661
288,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,259981,259981,259981,259981,259981,259981,259981,259981,259981,259981

In [41]:
death1 = death.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='Date',value_name='Death')
death1

,Province/State,Country/Region,Lat,Long,Date,Death
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0
...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,5708
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,0
311250,NaN,Yemen,15.552727,48.516388,1/2/23,2159
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,4024
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,5637

In [42]:
confirmed1 = confirmed.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='Date',value_name='Cause')
confirmed1

,Province/State,Country/Region,Lat,Long,Date,Cause
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0
...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,703228
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,535
311250,NaN,Yemen,15.552727,48.516388,1/2/23,11945
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,334661
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,259981

In [43]:
covide19 = confirmed1.merge(death1,on=['Province/State','Country/Region','Lat','Long','Date'])[['Country/Region','Date','Cause','Death']]

In [56]:
covide19[covide19['Country/Region'] == 'India']

       Country/Region      Date     Cause   Death
148             India   1/22/20         0       0
437             India   1/23/20         0       0
726             India   1/24/20         0       0
1015            India   1/25/20         0       0
1304            India   1/26/20         0       0
...               ...       ...       ...     ...
309956          India  12/29/22  44679382  530699
310245          India  12/30/22  44679608  530702
310534          India  12/31/22  44679873  530705
310823          India    1/1/23  44680046  530707
311112          India    1/2/23  44680180  530707

[1077 rows x 4 columns]