In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pt

In [2]:
date = pd.read_csv('data/orders.csv')
time = pd.read_csv('data/messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

#### Change datatype into datetime

In [5]:
#date is object we need to chnage it into datatime datatype
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

### Working with date

In [7]:
#Change the datatype of date column
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

#### Extract Year

In [9]:
# Extracting year
date['date_year'] = date['date'].dt.year

In [10]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

#### Extract month no

In [11]:
# Extracting month no
date['date_month_no'] = date['date'].dt.month

In [12]:
date.head(5)

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

#### Extract month name

In [13]:
date['date_month_name'] = date['date'].dt.month_name()

In [14]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

#### Extract day

In [15]:
# Extracting day
date['date_day'] = date['date'].dt.day

In [16]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

#### Extract day name

In [17]:
date['date_day_name'] = date['date'].dt.day_name()

In [18]:
date.head(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_day_name
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday

#### Extract day of week

In [19]:
#day of week
date['day_of_week'] = date['date'].dt.dayofweek

In [20]:
date.head(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_day_name,day_of_week
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday,1
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday,2
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday,1
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday,5
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,6

#### is weeked?

In [21]:
date['is weeked?'] =np.where(date['date_day_name'].isin(['Saturday','Sunday']),1,0)

In [22]:
date

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_day_name,day_of_week,is weeked?
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday,1,0
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday,2,0
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday,1,0
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday,5,1
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,6,1
...,...,...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,October,8,Monday,0,0
996,2018-12-06,5521,7,1,2018,12,December,6,Thursday,3,0
997,2019-05-07,487,26,14,2019,5,May,7,Tuesday,1,0
998,2019-03-03,1503,21,2,2019,3,March,3,Sunday,6,1
999,2019-10-15,6371,7,22,2019,10,October,15,Tuesday,1,0

#### Extract quarter

In [23]:
date['quarter'] = date['date'].dt.quarter

In [24]:
date

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_day_name,day_of_week,is weeked?,quarter
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday,1,0,4
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday,2,0,3
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday,1,0,4
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday,5,1,3
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,6,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,October,8,Monday,0,0,4
996,2018-12-06,5521,7,1,2018,12,December,6,Thursday,3,0,4
997,2019-05-07,487,26,14,2019,5,May,7,Tuesday,1,0,2
998,2019-03-03,1503,21,2,2019,3,March,3,Sunday,6,1,1
999,2019-10-15,6371,7,22,2019,10,October,15,Tuesday,1,0,4

#### Extract time elasped between dates

In [25]:
import datetime
today = datetime.datetime.today()

In [26]:
today

datetime.datetime(2024, 6, 17, 7, 7, 18, 186883)

In [27]:
dif = today-date['date']

In [28]:
dif

0     1651 days 07:07:18.186883
1     2133 days 07:07:18.186883
2     2064 days 07:07:18.186883
3     1766 days 07:07:18.186883
4     1989 days 07:07:18.186883
                 ...
995   2079 days 07:07:18.186883
996   2020 days 07:07:18.186883
997   1868 days 07:07:18.186883
998   1933 days 07:07:18.186883
999   1707 days 07:07:18.186883
Name: date, Length: 1000, dtype: timedelta64[ns]

In [29]:
dif.dt.days

0      1651
1      2133
2      2064
3      1766
4      1989
       ...
995    2079
996    2020
997    1868
998    1933
999    1707
Name: date, Length: 1000, dtype: int64

In [33]:
time.head(5)

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [35]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [37]:
time['date'] = pd.to_datetime(time['date'])

In [45]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   int32
 1   msg     1000 non-null   object
dtypes: int32(1), object(1)
memory usage: 11.8+ KB

In [47]:
#time['hour'] = time['date'].dt.hour

In [50]:
#time['Minute'] = time['date'].dt.minute
#time['Second'] = time['date'].dt.second