In [19]:
import pandas as pd
import numpy as np 
import seaborn as sns
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [22]:
df = pd.read_csv('data/Titanic-Train-Data.csv')[['Age','Pclass','SibSp','Parch','Survived']]

### Feature Construction

In [23]:
df.sample(5)

      Age  Pclass  SibSp  Parch  Survived
153  40.5       3      0      2         0
370  25.0       1      1      0         1
543  32.0       2      1      0         1
437  24.0       2      2      3         1
108  38.0       3      0      0         0

In [24]:
df.dropna(inplace=True)

In [25]:
df.isnull().sum()

Age         0
Pclass      0
SibSp       0
Parch       0
Survived    0
dtype: int64

In [26]:
X = df.drop(columns={'Survived'})
y = df.iloc[:,-1]

In [27]:
#croos validation 
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

0.6933333333333332

In [34]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1

In [35]:
X.sample(5)

      Age  Pclass  SibSp  Parch  Family_size
222  51.0       3      0      0            1
484  25.0       1      1      0            2
2    26.0       3      0      0            1
774  54.0       2      1      3            5
807  18.0       3      0      0            1

In [41]:
def myfunc(num):
    if num == 1:
        return 0
    elif num > 1 and num <= 4:
        return 1
    else:
        return 2

In [42]:
myfunc(7)

2

In [43]:
X['Family_type'] = X['Family_size'].apply(myfunc)

In [45]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [46]:
X.drop(columns={'SibSp','Parch','Family_size'},inplace=True)

In [47]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [49]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

0.7003174603174602

### Feature Splitting

In [50]:
df = pd.read_csv('data/Titanic-Train-Data.csv')

In [51]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [59]:
#Split the name
df['Title'] = df['Name'].str.split(',',expand=True)[1].str.split('.',expand=True)[0]

In [62]:
df[['Title','Name']]

     Title                                               Name
0       Mr                            Braund, Mr. Owen Harris
1      Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2     Miss                             Heikkinen, Miss. Laina
3      Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4       Mr                           Allen, Mr. William Henry
..     ...                                                ...
886    Rev                              Montvila, Rev. Juozas
887   Miss                       Graham, Miss. Margaret Edith
888   Miss           Johnston, Miss. Catherine Helen "Carrie"
889     Mr                              Behr, Mr. Karl Howell
890     Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [79]:
(df.groupby('Title').sum()['Survived']).sort_values(ascending=False)

Title
Miss            127
Mrs              99
Mr               81
Master           23
Dr                3
Mlle              2
Sir               1
Ms                1
Mme               1
the Countess      1
Col               1
Major             1
Lady              1
Jonkheer          0
Rev               0
Don               0
Capt              0
Name: Survived, dtype: int64