In [3]:
#!pip install optuna

In [2]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [6]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [7]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2024-11-05 08:36:51,133] A new study created in memory with name: no-name-4953ff66-99aa-40b4-938e-6eb0c512a6fc
[I 2024-11-05 08:36:51,811] Trial 0 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 190, 'max_depth': 8}. Best is trial 0 with value: 0.7616387337057727.
[I 2024-11-05 08:36:52,155] Trial 1 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 102, 'max_depth': 3}. Best is trial 0 with value: 0.7616387337057727.
[I 2024-11-05 08:36:52,386] Trial 2 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 51, 'max_depth': 16}. Best is trial 2 with value: 0.7709497206703911.
[I 2024-11-05 08:36:52,929] Trial 3 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 128, 'max_depth': 20}. Best is trial 3 with value: 0.7765363128491621.
[I 2024-11-05 08:36:53,228] Trial 4 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 79, 'max_depth': 11}. Best is trial 3 with value: 0.7765363128491621.
[I 2024-11-05 08:36:53,799] Trial 5 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 168, 'max_depth': 12}. Best is trial 3 with value: 0.7765363128491621.
[I 2024-11-05 08:36:54,458] Trial 6 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 195, 'max_depth': 18}. Best is trial 3 with value: 0.7765363128491621.
[I 2024-11-05 08:36:54,925] Trial 7 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 132, 'max_depth': 9}. Best is trial 3 with value: 0.7765363128491621.
[I 2024-11-05 08:36:55,144] Trial 8 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 67, 'max_depth': 4}. Best is trial 3 with value: 0.7765363128491621.
[I 2024-11-05 08:36:55,563] Trial 9 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 122, 'max_depth': 15}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:36:56,090] Trial 10 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 154, 'max_depth': 15}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:36:56,500] Trial 11 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 116, 'max_depth': 20}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:36:56,871] Trial 12 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 106, 'max_depth': 20}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:36:57,218] Trial 13 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:36:57,717] Trial 14 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 147, 'max_depth': 17}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:36:58,107] Trial 15 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 115, 'max_depth': 13}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:36:58,390] Trial 16 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 81, 'max_depth': 18}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:36:58,876] Trial 17 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 144, 'max_depth': 14}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:36:59,429] Trial 18 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 162, 'max_depth': 20}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:36:59,766] Trial 19 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 87, 'max_depth': 9}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:00,207] Trial 20 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 120, 'max_depth': 17}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:00,658] Trial 21 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 20}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:01,130] Trial 22 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 137, 'max_depth': 19}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:01,509] Trial 23 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 110, 'max_depth': 18}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:01,900] Trial 24 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 120, 'max_depth': 6}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:02,485] Trial 25 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 172, 'max_depth': 15}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:02,809] Trial 26 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 93, 'max_depth': 19}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:03,274] Trial 27 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 137, 'max_depth': 17}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:03,692] Trial 28 finished with value: 0.7728119180633146 and parameters: {'n_estimators': 122, 'max_depth': 12}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:04,207] Trial 29 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 153, 'max_depth': 10}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:04,829] Trial 30 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 183, 'max_depth': 16}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:05,252] Trial 31 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 123, 'max_depth': 20}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:05,725] Trial 32 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 129, 'max_depth': 19}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:06,171] Trial 33 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 98, 'max_depth': 20}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:06,568] Trial 34 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 112, 'max_depth': 19}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:07,079] Trial 35 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 141, 'max_depth': 16}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:07,506] Trial 36 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 123, 'max_depth': 20}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:07,973] Trial 37 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 18}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:08,210] Trial 38 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 65, 'max_depth': 13}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:08,583] Trial 39 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 103, 'max_depth': 17}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:09,030] Trial 40 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 115, 'max_depth': 19}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:09,477] Trial 41 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 130, 'max_depth': 19}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:09,950] Trial 42 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 127, 'max_depth': 20}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:10,466] Trial 43 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 135, 'max_depth': 18}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:10,996] Trial 44 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 9 with value: 0.7783985102420857.

[I 2024-11-05 08:37:11,410] Trial 45 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 111, 'max_depth': 19}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:11,759] Trial 46 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 94, 'max_depth': 16}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:12,332] Trial 47 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 162, 'max_depth': 14}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:12,851] Trial 48 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 143, 'max_depth': 18}. Best is trial 9 with value: 0.7783985102420857.
[I 2024-11-05 08:37:13,266] Trial 49 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 128, 'max_depth': 3}. Best is trial 9 with value: 0.7783985102420857.

In [8]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7783985102420857
Best hyperparameters: {'n_estimators': 122, 'max_depth': 15}

In [10]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(n_estimators=122,max_depth=15, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

## Samplers in Optuna <br>
#### 1)TPE <br>
#### 2)RandomSampler <br>
#### 3)GrideSearch

In [ ]:
#RandomSampler

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [11]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2024-11-05 08:53:52,434] A new study created in memory with name: no-name-cf873eb3-c44b-4391-846d-5dcbb2da7b05
[I 2024-11-05 08:53:52,868] Trial 0 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 141, 'max_depth': 3}. Best is trial 0 with value: 0.7579143389199254.
[I 2024-11-05 08:53:53,229] Trial 1 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 107, 'max_depth': 10}. Best is trial 1 with value: 0.7635009310986964.
[I 2024-11-05 08:53:53,717] Trial 2 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 148, 'max_depth': 6}. Best is trial 1 with value: 0.7635009310986964.
[I 2024-11-05 08:53:54,209] Trial 3 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 148, 'max_depth': 9}. Best is trial 1 with value: 0.7635009310986964.
[I 2024-11-05 08:53:54,424] Trial 4 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 59, 'max_depth': 12}. Best is trial 1 with value: 0.7635009310986964.
[I 2024-11-05 08:53:54,770] Trial 5 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 102, 'max_depth': 10}. Best is trial 1 with value: 0.7635009310986964.
[I 2024-11-05 08:53:55,304] Trial 6 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 159, 'max_depth': 11}. Best is trial 6 with value: 0.7690875232774674.
[I 2024-11-05 08:53:55,802] Trial 7 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 151, 'max_depth': 8}. Best is trial 6 with value: 0.7690875232774674.
[I 2024-11-05 08:53:56,190] Trial 8 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 112, 'max_depth': 9}. Best is trial 6 with value: 0.7690875232774674.
[I 2024-11-05 08:53:56,791] Trial 9 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 179, 'max_depth': 17}. Best is trial 9 with value: 0.7746741154562384.
[I 2024-11-05 08:53:57,439] Trial 10 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 199, 'max_depth': 8}. Best is trial 9 with value: 0.7746741154562384.
[I 2024-11-05 08:53:57,796] Trial 11 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 101, 'max_depth': 10}. Best is trial 9 with value: 0.7746741154562384.
[I 2024-11-05 08:53:58,148] Trial 12 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 97, 'max_depth': 9}. Best is trial 9 with value: 0.7746741154562384.
[I 2024-11-05 08:53:58,832] Trial 13 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 191, 'max_depth': 17}. Best is trial 9 with value: 0.7746741154562384.
[I 2024-11-05 08:53:59,307] Trial 14 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 138, 'max_depth': 12}. Best is trial 9 with value: 0.7746741154562384.
[I 2024-11-05 08:53:59,864] Trial 15 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 161, 'max_depth': 7}. Best is trial 9 with value: 0.7746741154562384.
[I 2024-11-05 08:54:00,169] Trial 16 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 86, 'max_depth': 18}. Best is trial 9 with value: 0.7746741154562384.
[I 2024-11-05 08:54:00,586] Trial 17 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 109, 'max_depth': 17}. Best is trial 9 with value: 0.7746741154562384.
[I 2024-11-05 08:54:01,196] Trial 18 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 163, 'max_depth': 7}. Best is trial 9 with value: 0.7746741154562384.
[I 2024-11-05 08:54:01,541] Trial 19 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 104, 'max_depth': 4}. Best is trial 9 with value: 0.7746741154562384.
[I 2024-11-05 08:54:02,167] Trial 20 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 184, 'max_depth': 8}. Best is trial 9 with value: 0.7746741154562384.
[I 2024-11-05 08:54:02,678] Trial 21 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 141, 'max_depth': 11}. Best is trial 9 with value: 0.7746741154562384.
[I 2024-11-05 08:54:03,155] Trial 22 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 149, 'max_depth': 5}. Best is trial 9 with value: 0.7746741154562384.
[I 2024-11-05 08:54:03,584] Trial 23 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 131, 'max_depth': 7}. Best is trial 23 with value: 0.7765363128491621.
[I 2024-11-05 08:54:04,043] Trial 24 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 126, 'max_depth': 14}. Best is trial 23 with value: 0.7765363128491621.
[I 2024-11-05 08:54:04,281] Trial 25 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 62, 'max_depth': 16}. Best is trial 23 with value: 0.7765363128491621.
[I 2024-11-05 08:54:04,651] Trial 26 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 113, 'max_depth': 3}. Best is trial 23 with value: 0.7765363128491621.
[I 2024-11-05 08:54:05,041] Trial 27 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 112, 'max_depth': 16}. Best is trial 27 with value: 0.7783985102420856.
[I 2024-11-05 08:54:05,355] Trial 28 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 94, 'max_depth': 6}. Best is trial 27 with value: 0.7783985102420856.
[I 2024-11-05 08:54:05,777] Trial 29 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 125, 'max_depth': 14}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:06,154] Trial 30 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 113, 'max_depth': 11}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:06,666] Trial 31 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 159, 'max_depth': 7}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:07,014] Trial 32 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 104, 'max_depth': 18}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:07,192] Trial 33 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 52, 'max_depth': 17}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:07,467] Trial 34 finished with value: 0.756052141527002 and parameters: {'n_estimators': 73, 'max_depth': 10}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:08,134] Trial 35 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 196, 'max_depth': 6}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:08,364] Trial 36 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 68, 'max_depth': 8}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:08,562] Trial 37 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 58, 'max_depth': 13}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:09,112] Trial 38 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 170, 'max_depth': 7}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:09,456] Trial 39 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 103, 'max_depth': 15}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:10,023] Trial 40 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 171, 'max_depth': 12}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:10,574] Trial 41 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 152, 'max_depth': 9}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:10,886] Trial 42 finished with value: 0.756052141527002 and parameters: {'n_estimators': 93, 'max_depth': 3}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:11,090] Trial 43 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 62, 'max_depth': 3}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:11,382] Trial 44 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 94, 'max_depth': 3}. Best is trial 29 with value: 0.7783985102420857.

[I 2024-11-05 08:54:11,841] Trial 45 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 18}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:12,218] Trial 46 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 106, 'max_depth': 9}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:12,441] Trial 47 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 56, 'max_depth': 18}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:12,855] Trial 48 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 117, 'max_depth': 11}. Best is trial 29 with value: 0.7783985102420857.
[I 2024-11-05 08:54:13,358] Trial 49 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 149, 'max_depth': 10}. Best is trial 29 with value: 0.7783985102420857.

In [12]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7783985102420857
Best hyperparameters: {'n_estimators': 125, 'max_depth': 14}

In [14]:
# GrideSearch
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [15]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2024-11-05 08:55:15,374] A new study created in memory with name: no-name-dd5b0fe3-723f-4936-9ddc-ebfcee070739
[I 2024-11-05 08:55:15,706] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2024-11-05 08:55:16,227] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2024-11-05 08:55:16,445] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2024-11-05 08:55:16,803] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2024-11-05 08:55:17,159] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2024-11-05 08:55:17,376] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2024-11-05 08:55:17,896] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2024-11-05 08:55:18,407] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2024-11-05 08:55:18,956] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2024-11-05 08:55:19,636] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2024-11-05 08:55:20,385] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2024-11-05 08:55:21,093] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2024-11-05 08:55:21,768] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2024-11-05 08:55:21,934] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2024-11-05 08:55:22,283] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2024-11-05 08:55:22,463] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [16]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

https://chatgpt.com/share/67299115-c45c-8000-af1e-5be53e59f665

## Optuna Visualizations

In [22]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2024-11-05 09:15:02,945] A new study created in memory with name: no-name-5c85653b-200c-49f4-adc9-a7062da36d74
[I 2024-11-05 09:15:03,226] Trial 0 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 74, 'max_depth': 3}. Best is trial 0 with value: 0.7616387337057727.
[I 2024-11-05 09:15:03,914] Trial 1 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 196, 'max_depth': 9}. Best is trial 0 with value: 0.7616387337057727.
[I 2024-11-05 09:15:04,431] Trial 2 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 148, 'max_depth': 13}. Best is trial 2 with value: 0.7709497206703911.
[I 2024-11-05 09:15:04,685] Trial 3 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 74, 'max_depth': 8}. Best is trial 3 with value: 0.7728119180633147.
[I 2024-11-05 09:15:05,092] Trial 4 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 116, 'max_depth': 20}. Best is trial 4 with value: 0.7783985102420857.
[I 2024-11-05 09:15:05,764] Trial 5 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 196, 'max_depth': 16}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:06,426] Trial 6 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:06,994] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 168, 'max_depth': 14}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:07,552] Trial 8 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 175, 'max_depth': 7}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:07,852] Trial 9 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 87, 'max_depth': 16}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:08,292] Trial 10 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 126, 'max_depth': 19}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:08,669] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 109, 'max_depth': 19}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:09,079] Trial 12 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 119, 'max_depth': 17}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:09,571] Trial 13 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 144, 'max_depth': 20}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:09,919] Trial 14 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 98, 'max_depth': 16}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:10,394] Trial 15 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 140, 'max_depth': 11}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:10,986] Trial 16 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 168, 'max_depth': 17}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:11,429] Trial 17 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 130, 'max_depth': 14}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:11,639] Trial 18 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 58, 'max_depth': 20}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:12,009] Trial 19 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 108, 'max_depth': 11}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:12,545] Trial 20 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 156, 'max_depth': 18}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:12,941] Trial 21 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 114, 'max_depth': 17}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:13,382] Trial 22 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 123, 'max_depth': 15}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:13,714] Trial 23 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 94, 'max_depth': 18}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:14,346] Trial 24 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 182, 'max_depth': 12}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:14,813] Trial 25 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 136, 'max_depth': 16}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:15,343] Trial 26 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 154, 'max_depth': 18}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:15,749] Trial 27 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 118, 'max_depth': 19}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:16,116] Trial 28 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:16,442] Trial 29 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 82, 'max_depth': 15}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:16,889] Trial 30 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 131, 'max_depth': 13}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:17,305] Trial 31 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 120, 'max_depth': 15}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:17,682] Trial 32 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 109, 'max_depth': 17}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:18,338] Trial 33 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 189, 'max_depth': 15}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:18,751] Trial 34 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 120, 'max_depth': 10}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:19,007] Trial 35 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 71, 'max_depth': 14}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:19,530] Trial 36 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 151, 'max_depth': 3}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:20,127] Trial 37 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 161, 'max_depth': 17}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:20,498] Trial 38 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 104, 'max_depth': 13}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:20,964] Trial 39 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 135, 'max_depth': 18}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:21,370] Trial 40 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 117, 'max_depth': 8}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:21,806] Trial 41 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 125, 'max_depth': 15}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:22,244] Trial 42 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 126, 'max_depth': 16}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:22,603] Trial 43 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 90, 'max_depth': 16}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:22,884] Trial 44 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 77, 'max_depth': 19}. Best is trial 5 with value: 0.7802607076350093.

[I 2024-11-05 09:15:23,414] Trial 45 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 144, 'max_depth': 12}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:24,076] Trial 46 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 195, 'max_depth': 14}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:24,283] Trial 47 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 57, 'max_depth': 16}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:24,876] Trial 48 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 174, 'max_depth': 19}. Best is trial 5 with value: 0.7802607076350093.
[I 2024-11-05 09:15:25,234] Trial 49 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 101, 'max_depth': 17}. Best is trial 5 with value: 0.7802607076350093.

In [23]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 196, 'max_depth': 16}

In [24]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [25]:
# 1. Optimization History
plot_optimization_history(study).show()

In [26]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [27]:
# 3. Slice Plot
plot_slice(study).show()

In [28]:
# 4. Contour Plot
plot_contour(study).show()

In [29]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

### Optimizing Multiple ML Models

In [30]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [31]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [32]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=100)  # Run 100 trials to find the best hyperparameters

[I 2024-11-05 11:19:59,660] A new study created in memory with name: no-name-1d1dc9cd-debb-41ad-9539-305a1cd5feee
[I 2024-11-05 11:20:00,208] Trial 0 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 201, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 0 with value: 0.7728119180633147.
[I 2024-11-05 11:20:01,264] Trial 1 finished with value: 0.6983240223463687 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 110, 'learning_rate': 0.022961874974007902, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.7728119180633147.
[I 2024-11-05 11:20:01,464] Trial 2 finished with value: 0.7430167597765364 and parameters: {'classifier': 'RandomForest', 'n_estimators': 79, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.7728119180633147.
[I 2024-11-05 11:20:02,435] Trial 3 finished with value: 0.7672253258845437 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 221, 'learning_rate': 0.010665251902652847, 'max_depth': 17, 'min_samples_split': 3, 'min_samples_leaf': 10}. Best is trial 0 with value: 0.7728119180633147.
[I 2024-11-05 11:20:02,469] Trial 4 finished with value: 0.7188081936685289 and parameters: {'classifier': 'SVM', 'C': 4.8264735489330635, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 0 with value: 0.7728119180633147.
[I 2024-11-05 11:20:03,357] Trial 5 finished with value: 0.7337057728119181 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 260, 'learning_rate': 0.29769252590918954, 'max_depth': 16, 'min_samples_split': 8, 'min_samples_leaf': 9}. Best is trial 0 with value: 0.7728119180633147.
[I 2024-11-05 11:20:03,661] Trial 6 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 90, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 0 with value: 0.7728119180633147.
[I 2024-11-05 11:20:03,702] Trial 7 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 9.034112069943367, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:05,267] Trial 8 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 278, 'learning_rate': 0.04518346649960872, 'max_depth': 18, 'min_samples_split': 10, 'min_samples_leaf': 8}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:05,725] Trial 9 finished with value: 0.7579143389199254 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 75, 'learning_rate': 0.03873848344988202, 'max_depth': 17, 'min_samples_split': 10, 'min_samples_leaf': 6}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:05,939] Trial 10 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 93.89407682396889, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:06,161] Trial 11 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 76.20229257507353, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:06,350] Trial 12 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 73.1024648171001, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:06,380] Trial 13 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.6330501363891576, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:06,417] Trial 14 finished with value: 0.7523277467411545 and parameters: {'classifier': 'SVM', 'C': 0.1520728962777884, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:06,449] Trial 15 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 9.056232697560072, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:06,514] Trial 16 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 13.981349318724835, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:06,541] Trial 17 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.3868623402347124, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:06,585] Trial 18 finished with value: 0.7039106145251397 and parameters: {'classifier': 'SVM', 'C': 24.24229302914405, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:06,610] Trial 19 finished with value: 0.7486033519553073 and parameters: {'classifier': 'SVM', 'C': 0.737288483024632, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:07,112] Trial 20 finished with value: 0.7541899441340782 and parameters: {'classifier': 'RandomForest', 'n_estimators': 148, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:07,335] Trial 21 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 79.42783053607435, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:07,434] Trial 22 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 33.8404032101356, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:07,627] Trial 23 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 85.07513564964306, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:07,665] Trial 24 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 32.2915559064183, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:07,712] Trial 25 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 8.624906874705667, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:07,829] Trial 26 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 38.00076111203491, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:07,899] Trial 27 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 18.357395060578163, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:07,924] Trial 28 finished with value: 0.6890130353817505 and parameters: {'classifier': 'SVM', 'C': 91.16280561015333, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:08,430] Trial 29 finished with value: 0.7783985102420856 and parameters: {'classifier': 'RandomForest', 'n_estimators': 149, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:08,609] Trial 30 finished with value: 0.7579143389199254 and parameters: {'classifier': 'RandomForest', 'n_estimators': 50, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:08,754] Trial 31 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 56.10572816936623, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:08,897] Trial 32 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 48.14490094970738, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.

[I 2024-11-05 11:20:09,237] Trial 33 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 85.59077942109079, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:09,300] Trial 34 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 13.898100092907576, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:10,644] Trial 35 finished with value: 0.7281191806331471 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 237, 'learning_rate': 0.18843031680174518, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 7}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:10,671] Trial 36 finished with value: 0.7374301675977654 and parameters: {'classifier': 'SVM', 'C': 0.3803426688139391, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:11,643] Trial 37 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 297, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:12,942] Trial 38 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 181, 'learning_rate': 0.11624518396960656, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:12,984] Trial 39 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 48.71808514044693, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:13,014] Trial 40 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.662382787817296, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:13,047] Trial 41 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.574126083846683, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:13,078] Trial 42 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.412726547877904, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:13,110] Trial 43 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.460973206078462, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:13,912] Trial 44 finished with value: 0.7411545623836125 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 144, 'learning_rate': 0.0910683974142608, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 10}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:13,954] Trial 45 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 6.021401893841149, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:13,978] Trial 46 finished with value: 0.7206703910614526 and parameters: {'classifier': 'SVM', 'C': 4.489245997414076, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:14,141] Trial 47 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 55.88063483805995, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:14,451] Trial 48 finished with value: 0.7523277467411545 and parameters: {'classifier': 'RandomForest', 'n_estimators': 112, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:14,488] Trial 49 finished with value: 0.7374301675977654 and parameters: {'classifier': 'SVM', 'C': 23.07409463222587, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:15,951] Trial 50 finished with value: 0.7616387337057727 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 249, 'learning_rate': 0.012325410571087542, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 6}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:16,009] Trial 51 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.170568395499226, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:16,051] Trial 52 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 5.908998065433964, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:16,078] Trial 53 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.4252448770072712, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:16,109] Trial 54 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 8.837968069793634, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:16,174] Trial 55 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 16.59378015629826, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:16,352] Trial 56 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 62.51988148620911, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:16,376] Trial 57 finished with value: 0.7001862197392924 and parameters: {'classifier': 'SVM', 'C': 34.742511941815366, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:16,604] Trial 58 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 99.19852530216455, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:16,631] Trial 59 finished with value: 0.7337057728119181 and parameters: {'classifier': 'SVM', 'C': 0.8538919273327377, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:17,184] Trial 60 finished with value: 0.7783985102420857 and parameters: {'classifier': 'RandomForest', 'n_estimators': 187, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:17,373] Trial 61 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 68.49570166949135, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:17,458] Trial 62 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 25.058310735839584, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:17,679] Trial 63 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 70.96121484711932, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:17,800] Trial 64 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 42.059379706823485, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:17,829] Trial 65 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 1.8449965041086507, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:17,868] Trial 66 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 24.208680664848632, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:18,118] Trial 67 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 75.64502654335848, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.

[I 2024-11-05 11:20:19,781] Trial 68 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 213, 'learning_rate': 0.022971803439813074, 'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:19,875] Trial 69 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 32.88417291870171, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:19,917] Trial 70 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 6.534768683170833, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:20,171] Trial 71 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 98.67466599010231, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:20,299] Trial 72 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 45.24967134859288, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:20,490] Trial 73 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 66.09777586512291, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:20,540] Trial 74 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 10.413161503780042, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:21,538] Trial 75 finished with value: 0.7541899441340781 and parameters: {'classifier': 'RandomForest', 'n_estimators': 297, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:21,563] Trial 76 finished with value: 0.702048417132216 and parameters: {'classifier': 'SVM', 'C': 51.12672699484015, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:21,656] Trial 77 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 28.94303060904503, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:21,725] Trial 78 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 17.206010004766426, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:22,087] Trial 79 finished with value: 0.7560521415270017 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 120, 'learning_rate': 0.09012890084082588, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 2}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:22,117] Trial 80 finished with value: 0.7094972067039106 and parameters: {'classifier': 'SVM', 'C': 0.12253910244357152, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:22,375] Trial 81 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 83.14755096714829, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:22,492] Trial 82 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 39.86888511432232, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:22,631] Trial 83 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 53.48357865275604, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:22,678] Trial 84 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 81.10059400592255, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:22,921] Trial 85 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 99.63213158888196, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:22,956] Trial 86 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.600217036535384, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:23,158] Trial 87 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 54, 'max_depth': 15, 'min_samples_split': 3, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:23,327] Trial 88 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 57.00597250506331, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:23,530] Trial 89 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 74.6318111182442, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:23,639] Trial 90 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 40.37279296354641, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:23,683] Trial 91 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 6.936997094300982, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:23,750] Trial 92 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 13.521112304228499, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:23,796] Trial 93 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 8.520921477930846, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:23,823] Trial 94 finished with value: 0.7206703910614526 and parameters: {'classifier': 'SVM', 'C': 2.1791557821395307, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 7 with value: 0.7858472998137801.
[I 2024-11-05 11:20:23,850] Trial 95 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2520324970435341, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 95 with value: 0.7858472998137803.
[I 2024-11-05 11:20:23,882] Trial 96 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.36692569860307406, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 95 with value: 0.7858472998137803.
[I 2024-11-05 11:20:25,092] Trial 97 finished with value: 0.7448789571694601 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 170, 'learning_rate': 0.025381584431159326, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 95 with value: 0.7858472998137803.
[I 2024-11-05 11:20:25,168] Trial 98 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 19.644884861020792, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 95 with value: 0.7858472998137803.
[I 2024-11-05 11:20:25,197] Trial 99 finished with value: 0.7262569832402234 and parameters: {'classifier': 'SVM', 'C': 0.3020337206427196, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 95 with value: 0.7858472998137803.

In [33]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.2520324970435341, 'kernel': 'linear', 'gamma': 'scale'}
Best trial accuracy: 0.7858472998137803

In [34]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.772812,2024-11-05 11:19:59.661361,2024-11-05 11:20:00.208606,0 days 00:00:00.547245,NaN,False,RandomForest,NaN,NaN,NaN,13.0,8.0,8.0,201.0,COMPLETE
1,1,0.698324,2024-11-05 11:20:00.209606,2024-11-05 11:20:01.263471,0 days 00:00:01.053865,NaN,NaN,GradientBoosting,NaN,NaN,0.022962,10.0,1.0,4.0,110.0,COMPLETE
2,2,0.743017,2024-11-05 11:20:01.265750,2024-11-05 11:20:01.463356,0 days 00:00:00.197606,NaN,False,RandomForest,NaN,NaN,NaN,3.0,3.0,8.0,79.0,COMPLETE
3,3,0.767225,2024-11-05 11:20:01.465356,2024-11-05 11:20:02.435975,0 days 00:00:00.970619,NaN,NaN,GradientBoosting,NaN,NaN,0.010665,17.0,10.0,3.0,221.0,COMPLETE
4,4,0.718808,2024-11-05 11:20:02.436979,2024-11-05 11:20:02.469421,0 days 00:00:00.032442,4.826474,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.785847,2024-11-05 11:20:23.824605,2024-11-05 11:20:23.850583,0 days 00:00:00.025978,0.252032,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.782123,2024-11-05 11:20:23.850583,2024-11-05 11:20:23.882911,0 days 00:00:00.032328,0.366926,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.744879,2024-11-05 11:20:23.883930,2024-11-05 11:20:25.091341,0 days 00:00:01.207411,NaN,NaN,GradientBoosting,NaN,NaN,0.025382,10.0,4.0,9.0,170.0,COMPLETE
98,98,0.785847,2024-11-05 11:20:25.093343,2024-11-05 11:20:25.168329,0 days 00:00:00.074986,19.644885,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.726257,2024-11-05 11:20:25.169455,2024-11-05 11:20:25.197309,0 days 00:00:00.027854,0.302034,NaN,SVM,auto,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [35]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 77
GradientBoosting    12
RandomForest        11
Name: count, dtype: int64

In [36]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.744258
RandomForest        0.762147
SVM                 0.768894
Name: value, dtype: float64

In [37]:
# 1. Optimization History
plot_optimization_history(study).show()

In [38]:
# 3. Slice Plot
plot_slice(study).show()

In [39]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()